<link href="https://fonts.googleapis.com/css?family=Roboto|Source+Sans+Pro:300,400,600|Ubuntu+Mono&amp;subset=latin-ext" rel="stylesheet">

```{r,include=FALSE,eval=knitr::opts_knit$get("rmarkdown.pandoc.to")=="html"}
# Enables Font Awesome in HTML based bookdown outputs.
fa <- rmarkdown::html_dependency_font_awesome()
fa$attachment <- "fonts/fontawesome-webfont.ttf"
htmltools::tagList(fa)
```

```{r,echo=FALSE,message=FALSE,warning=FALSE,results='hide'}
# run setup code

# load libraries
library(knitr) # runs pandoc
library(bookdown) # for markdown

# knitr options
knitr::opts_knit$set(progress=TRUE,verbose=TRUE)
knitr::opts_chunk$set(dev="svg",
                      results="hold",
                      fig.show="hold",
                      fig.align="left",
                      echo = FALSE,
                      message=FALSE, 
                      warning=FALSE,
                      cache = TRUE, 
                      fig.align ="center",
                      fig.height = 6,
                      fig.width = 10)
```

```{r theme}
theme_Publication <- function(base_size=12, base_family="Helvetica", position_legend = "bottom", angulo_x = 0, angulo_y = 0) {
      library(grid)
      library(ggthemes)
      (ggthemes::theme_foundation(base_size=base_size, base_family=base_family)
       + theme(plot.title = element_text(size = rel(0.6), hjust = 0),
               text = element_text(),
               panel.background = element_rect(colour = NA),
               plot.background = element_rect(colour = NA),
               panel.border = element_rect(colour = NA),
               axis.title = element_text(size = rel(0.9)),
               axis.title.y = element_text(angle=90,vjust =2),
               axis.title.x = element_text(vjust = -0.2),
               # axis.text = element_text(),
               axis.text.x = element_text(angle = angulo_x),
               axis.text.y = element_text(angle = angulo_y),
               axis.line = element_line(colour="black"),
               axis.ticks = element_line(),
               panel.grid.major = element_line(colour="#f0f0f0"),
               panel.grid.minor = element_blank(),
               legend.key = element_rect(colour = NA),
               legend.position = position_legend,
               legend.direction = "horizontal",
               legend.key.size= unit(0.2, "cm"),
               legend.margin = unit(0, "cm"),
               # legend.spacing = unit(0, "cm"),
               legend.title = element_text(face="italic"),
               plot.margin=unit(c(10,5,5,5),"mm"),
               strip.background=element_rect(colour="#f0f0f0",fill="#f0f0f0"),
               strip.text = element_text(face="bold")
          ))
}

scale_fill_Publication <- function(...){
      library(scales)
      discrete_scale("fill","Publication",manual_pal(values = c("#386cb0","#fdb462","#7fc97f","#ef3b2c","#662506","#a6cee3","#fb9a99","#984ea3","#ffff33")), ...)

}

scale_colour_Publication <- function(...){
      library(scales)
      discrete_scale("colour","Publication",manual_pal(values = c("#386cb0","#fdb462","#7fc97f","#ef3b2c","#662506","#a6cee3","#fb9a99","#984ea3","#ffff33")), ...)

}
```

<!-- <script type="text/x-mathjax-config"> -->
<!--   MathJax.Hub.Config({ -->
<!--     TeX: { equationNumbers: { autoNumber: "AMS" } }, -->
<!--   }); -->
<!-- </script> -->
<!-- <style> -->
<!-- .mjx-mrow a { -->
<!--   color: black; -->
<!--   pointer-events: none; -->
<!--   cursor: default; -->
<!-- } -->
<!-- </style> -->

<!-- <script type="text/x-mathjax-config"> -->
<!-- MathJax.Hub.Config({ -->
<!--   TeX: { -->
<!--       equationNumbers: { -->

<!--             autoNumber: "all", -->
<!--             formatNumber: function (n) {return '9.'+n} -->
<!--       } -->
<!--   } -->
<!-- }); -->
<!-- </script> -->

