# Introducción {#intro}

<!-- Presentación de la CB, componentes y su utilización -->
El análisis teórico de la dinámica agregada del mercado laboral ha estado organizado en base a dos relaciones, la curva de Phillips y la curva de Beverige [@Blanchard1989]. La curva de Beveridge (en adelante CB) analizada por primera vez por @Beveridge y @Dicks-Mireaux1958 plantea una relación negativa entre la tasa de vacantes laborales y la tasa de desempleo y, resume información esencial sobre el funcionamiento del mercado de trabajo y shocks que afecten al mismo [@Blanchard1989]. Las vacantes se entienden como aquella posición dentro de la firma que el empleador busca cubrir activamente durante un periodo de referencia mientras los desocupados se definen como aquellas personas que durante un periodo de tiempo buscan trabajo remunerado activamente pero no logran obtenerlo.<!-- ^[Ambas variables suelen ser normalizadas por la población económicamente activa (PEA), personas que pertenecer a la población en edad de trabajar (PET) y buscar hacerlo activamente.] -->

El objetivo principal de esta investigación es profundizar en esta relación negativa y probar si existe estabilidad parámetrica a lo largo del tiempo, por lo tanto, la pregunta de investigación busca responder si la curva de Beveridge de Uruguay entre 1980 y 2019 presenta cambios de pendientes y/o traslados paralelos en cualquier momento del periodo considerado. La hipótesis sostenida es que la relación entre vacantes y desempleo no puede ser estable para el periodo de estudio.

La medición de la tasa de trabajadores desocupados se mide regularmente a lo largo del mundo con una metodología estandarizada y validada. Mientras las vacantes <!-- Las vacantes se utilizan como proxy de la demanda laboral y se cuantifican mediante los avisos laborales publicados en la prensa o portales de Internet.  --> son raramente calculadas bajo una metodología sistemática, no suelen ser recolectadas, ni existen encuestas al respecto a excepción de algunos países, especialmente de la OCDE [@Elsby2015].<!-- ^[Una explicación es que la recolección y medición de vacantes es una tarea compleja para las oficinas estadísticas encargadas de recabar dicha información, debido a la difícil definición de qué es una vacante y cuando una empresa identifica que existen vacantes y buscan llenarla [@Elsby2015].] --> En Uruguay no existe una serie de vacantes oficial que se publique de forma pública y sistemática. Por lo tanto, el primer objetivo específico de este trabajo es crear el primer indicador de vacantes laborales reproducible, extenso y sistemático. La base de datos que se construye abarca casi 40 años, incorporando para los últimos quince años tres fuentes de datos y el análisis de datos a traves de _text mining_ [@Jurasky2019].

<!-- Pregunta de investigación -->
Finalizado el indicador se obtiene el primer resultado empírico, el cual es una correlación positiva con el producto hasta el año 2013 y una relación negativa con la tasa de desempleo. 
<!-- El objetivo principal de esta investigación es profundizar en esta relación negativa y probar si existe estabilidad parámetrica a lo largo del tiempo, por lo tanto, la pregunta de investigación busca responder si la curva de Beveridge de Uruguay entre 1980 y 2019 presenta cambios de pendientes y/o traslados paralelos en cualquier momento del periodo considerado. -->

<!-- Fuentes de datos -->
Para responder la pregunta de investigación se utiliza la tasa de desempleo calculada por el Instituto Nacional de Estadística (INE), la Encuesta Continua de Hogares (ECH) sistematizada por parte del Instituto de Economía (IECON), el Producto Interno Bruto (PIB) calculado por el Banco Central del Uruguay (BCU) y el indicador de vacantes laborales construido a partir de avisos de el diario El País (sección _Gallito_), los portales laborales _Buscojobs_, _Computrabajo_, _Uruguay Concursa_, el Índice Ceres de Demanda Laboral (ICDL) y los datos de vacantes provenientes de @Rama1988 y @Urrestarazu1997.

<!-- Explicación de la hipótesis (fundamentos teóricos)-->
La hipótesis sostenida es que la relación entre vacantes y desempleo no puede ser estable para el periodo de estudio, deberíamos observar al menos uno de los siguientes efectos: cambios de pendiente, traslados de la CB y/o alteraciones en la varianza de los errores en un modelo lineal. <!-- Esta parte debería mejorar la redacción --> Para fundamentar la hipótesis y explicar los traslados de la CB se utiliza la teoría de búsqueda y emparejamiento o marco DMP [@Pissarides2000], basado fundamentalmente en los trabajos de @Pissarides1985, @Mortensen1994 y @Diamond1982.^[Adicionalmente están los los trabajos de @Hall1979, @Pissarides1979, @Diamond1982B]

Los cambios observados en la CB pueden deberse principalmente a factores institucionales [@Gujarati1972;@Blanchard2000;@Nickell2002; @Bouvet2012], factores tecnológicos [@Elsby2015;@Lubik2013] o a factores asociados al ciclo económico [@Abraham1987;@Blanchard1989;@Hobijn2013]. Según el marco DMP [@Pissarides2000] los movimientos sobre la curva se asocian a factores de ciclo económico mientras traslados paralelos (mayor o menor desempleo para una tasa de vacantes dada) se interpretan como cambios estructurales que afectan el _matching_ entre puestos y trabajadores desempleados.<!-- Falta hablar de los movimientos (ej, shock de demanda, de oferta, sectoriales) --> Los traslados pueden ser por aumentos en la tasa de destrucción de puestos laborales o modificaciones en la función de matching. Cambios en la función de matching pueden deberse a cambios en los costos de contratación, despido, seguro de desempleo y salario mínimo [@Bouvet2012]; existencia de derecho a huelga, ocupación y sindicalización [@Nickell2002]; facilidad de la mano de obra para moverse geográficamente [@Bewley1979; @Hobijn2013]; modificaciones en el comportamiento de las firmas [@Haltiwanger2012] y, alteraciones tecnológicas que puedan cambiar los costos de búsqueda y la probabilidad de encontrarse [@Barnichon2012;@Elsby2015].

<!-- Reescribir, primero factores institucionales, luego tecnológicos y finalmente cíclicos. -->
<!-- Según el marco DMP los movimientos sobre la curva se asocian a factores de ciclo económico mientras traslados paralelos (mayor o menor desempleo para una tasa de vacantes dada) se interpretan como cambios estructurales que afectan el _matching_ entre puestos y trabajadores desempleados [@Bouvet2012]. Los traslados pueden ser por aumentos en la tasa de destrucción de puestos laborales o modificaciones en la función de matching. Cambios en la función de matching pueden deberse a cambios en los costos de contratación y despido, salario mínimo, existencia de derecho a huelga y ocupación, sindicalización, facilidad de la mano de obra para moverse geográficamente (cambios en la PEA), modificaciones en las habilidades de los trabajadores y alteraciones tecnológicas que puedan cambiar los costos de búsqueda y la probabilidad de encontrarse, como la creación de portales laborales en Internet. <!-- Falta una explicación de los cambios de ciclo económico -->

<!-- Explicación de la hipótesis fundamentos empíricos: estructurales y ciclo -->
Muchas de estas causas estructurales se observan en Uruguay. Por ejemplo, en la década de 1980 retorna la democracia (1985), con ella aumenta la sindicalización y se reinstauran los consejos de salarios los cuales funcionaron junto a una elevada negociación por rama de actividad del orden del 94% [@Filgueira2003].^[Entre 1985 y 1999 la negociación por rama era de 94 %, entre 1990-1994 de 76.4% y en 1995-1999 de 35%. La negociación por empresa entre 1985-1989 era de 6%, entre 1990-1994 de 21.2% y entre 1995-1999 de 64.4% [@Filgueira2003]. El trabajo de @Quinones2001 muestra la caída de la cantidad de afiliados a sindicatos privados entre 1987 y 2000. No hay datos para periodos previos, sin embargo, el aumento planteado es relativo al periodo previo de dictadura en el cual la central CNT fue declarada ilegal, luego el decreto 622/73 permitió la creación de sindicatos pero mediante elecciones secretas.] En los años 90, el efecto es inverso, disminuye la sindicalización prácticamente a la mitad [@Quinones2001], cae la negociación por rama de actividad a un 35% [@Filgueira2003] y se dejan de convocar los consejos de salarios a partir de 1992 [@Antia2001]. A partir de 2005, se promulgan un conjunto de reformas estructurales que producen un cambio sustancial en las reglas de juego de la economía [@Bergara2017]. Los gobiernos vuelven a convocar los consejos de salarios, fomentan la negociación por rama de actividad, establecen la protección de los trabajadores en procesos de terciarización, aumentan el salario mínimo, limitan la jornada laboral de trabajadores rurales, regulan el trabajo del servicio doméstico y aprueban la ley de responsabilidad penal empresarial [@Bergara2017].^[Esto pudo aumentar el poder de negociación de los trabajadores por el aumento de la densidad sindical, ya que, la central obrera PIT-CNT cuadruplicó sus afiliados entre 2005 y 2020.] 

Además hay cambios tecnológicos relevantes como la penetración de Internet que fomentan el ingreso de nuevos actores en el sector de prensa laboral apareciendo los portales _Buscojobs_, _Computrabajo_, <!-- ^[Dichos portales comienzan a funcionar formalmente en Uruguay a partir de 2003 en el caso de _Computrabajo_ y 2007 _Buscojobs_, aunque en torno a 2009-2010 comienzan a tener un nivel de actividad relevante]  --> el funcionamiento de _Gallito_ a través de Internet y la creación del portal _Uruguay Concursa_ donde se centralizan las solicitudes de empleos públicos. Por último, la crisis 2002 genera una enorme emigración de población y desalienta a los trabajadores, lo cual repercute en una caída importante de la población económicamente activa (PEA) como se observa en la Figura \@ref(fig:PeaMontevideo).

<!-- Causas cíclicas luego --> Las dos crisis económicas previamente mencionadas, sumado a una breve recesión en 1995 pueden dar explicaciones asociadas al ciclo económico. Entre 1982-1984 la crisis de la _tablita_ genera una caída de casi 16% del producto, el salario real medio cae un 28% y el desempleo en Montevideo llega al 14% [@Antia2001]. Entre 1985-2000 el índice de horas trabajadas cae a la mitad, los índices de productividad se duplican [@Quinones2001] y la economía tiene años (1996-1998) de elevado crecimiento de la actividad por sobre el 5% [@Antia2001]. Posteriormente, entre 1999 y 2003 comienza una recesión (caída de 3.8% y 7.7% en la tasa de crecimiento) que culmina en una grave crisis económica y social. Desde 2003 en adelante la economía crece de forma sistemática (entre 2004 y 2011 la tasa de crecimiento oscila entre 4.1% y 7.8%), hay un shock externo de commodities y un flujo importante de inversión extranjera, con lo cual hasta 2011 la tasa promedio anual de variación del IVF del PIB es 5.9% y el desempleo se ubica en sus menores valores (5-6%) en cuarenta años.

Dada esta multiplicidad de transformaciones, se buscan estrategías empíricas lo suficientemente flexibles para captar posibles cambios parámetricos continuos o discretos. <!-- Los test de fluctuación generalizada [@Kuan1995;@Ploberger1989;@Brown1975;@Society1988] y los test basados en el estadístico F [@Andrews1993;@Andrews1994;@Hansen1992] --> A modo de exploración se utilizan los test de fluctuación generalizada [@Kuan1995;@Ploberger1989;@Brown1975;@Society1988] con los cuales se encuentra evidencia de posibles quiebres estructurales tanto en media como en varianza. Se profundiza con test de quiebres estructurales de tipo F generalizados que no requieren definir el momento del cambio estructural para poner a prueba la hipótesis nula de no existencia de un cambio estructural en la relación de vacantes y desempleo [@Andrews1991;@Hansen1992;@Andrews1993;@Andrews1994], de esta forma se encuentra una modificación en la media del proceso en 1990, resultado obtenido previamente por @Urrestarazu1997. Posteriormente, se utilizan test generalizados los cuales permiten obtener múltiples cambios estructurales sin imponer los momentos de dichos quiebres y, se agrega la posibilidad de un quiebre en la varianza de la relación [@BaiPerron1998;@BaiPerron2003;@Zeileis2010]. De esta forma se obtienen cuatro CB, todas con relación negativa entre vacantes y desempleo y, con alteraciones tanto en la pendiente como traslados paralelos. Las causas podrían estar asociadas a factores cíclicos, institucionales o tecnológicos.

A continuación se pleantean vectores autorregresivos con parámetros variables y volatilidad estocástica, TVP-VAR o TVP-VAR-SV [@Nakajima2011;@Benati2013;@Primiceri2005;@Lubik2016b], identificado bajo un modelo básico de búsqueda y emparejamiento, con restricciones de identificación de Cholesky y estimado de forma bayesiana mediante el muestreo de Gibbs. Esta estrategia se elige en la medida que si bien es lineal condicional en los parámetros, el modelo completo es altamente no lineal y extremadamente flexible al permitir que los coeficientes del modelo (interceptos, rezagos y covarianzas de errores) evolucionen como un paseo aleatorio [@Lubik2016b]. De su estimación surge que tanto interceptos como rezagos no cambian a lo largo del tiempo, aunque si lo hace levemente la varianza de los errores, indicando que alteraciones en la CB podrían ser causadas por shocks de distinta indole, por ejemplo, de productividad. Esto se fortalece con el análisis de las funciones de impulso respuesta (FIR) que muestran como un shock de producto a vacantes genera un efecto positivo y duradero, mientras en el desempleo el efecto es negativo.

Ambas estrategias concuerdan en que las varianzas de los errores se modifican a lo largo del tiempo, sin embargo llegan a conclusiones diferentes en cuanto a los interceptos y rezagos. Es un resultado común en la literatura de TVP-VAR la posibilidad de no encontrar variabilidad en interceptos y rezagos pese a que si debería existir y, asociarlo a la matriz de varianzas y covarianzas [@Lubik2016b]. Los resultados indican distintas fases de la CB que pueden deberse a cambios por el ciclo económico, dadas las crisis y periodos de alto y bajo crecimiento, alteraciones de la PEA o shocks de productividad. A mejoras tecnológicas que faciliten el _match_ como la creación de portales laborales web. O la causa puede ser de origen institucional debido a la elevada cantidad de reformas estructurales que tuvo la economía, en especial de la década de 2000 en adelante. Por último, la enorme disminución observada en las vacantes laborales y el leve aumento del desempleo (especialmente en la comparación histórica) indican que el mercado laboral uruguayo debería haberse vuelto notoriamente más eficiente en su proceso de matching pese a reformas institucionales que podrían ir sentido opuesto [@Nickell2002;@Bouvet2012]. Sin embargo, para corroborar esta afirmación es necesario agregar un análisis de flujos laborales, identificar shocks de productividad y aislar el efecto de otras variables relevantes que puedan tener influencia. Es de interés que trabajos posteriores se enfoquen en identificar las causas de los movimientos en la CB, lo cual es de suma importancia para la política económica.

<!-- Por ejemplo, en la década de los noventa Uruguay transitó una apertura de su cuenta corriente y de capitales lo cual genero un efecto relevante en el mercado laboral, ya que, las empresas locales no fueron capaces de competir con los productos importados, siendo un periodo de crecimiento económico y alto desempleo [@Antia2001]. El gobierno dejó de participar de los consejos de salarios a partir de 1992 dando libertad de acción a la negociación entre empresas y trabajadores [@Antia2001]. Fue una clara promoción a la negociación por empresa en contraposición a la negociación por rama de actividad, mientras la primera aumento de forma considerable la segunda cayó abruptamente [@Filgueira2003].  -->

<!-- La hipótesis se fundamenta en las transformaciones mencionadas, ya que, según -->
<!-- el marco DMP shocks o cambios estructurales en la economía generan corrimientos -->
<!-- de la curva, debido a un aumento o disminución del mismatch. Al igual que políticas -->
<!-- públicas de carácter institucional que busquen aumentar la efectividad del match en -->
<!-- el mercado laboral volviéndolo más eficiente (Elsby et al., 2015; Rodenburg, 2007) o -->
<!-- modificaciones tecnológicas que puedan cambiar los costos de búsqueda tanto para -->
<!-- trabajadores como empresas así como la probabilidad de encontrarse -->

<!-- @Elsby2015 muestran que la CB se utiliza a nivel macroeconómico como un marco de análisis para el entendimiento de los mercados laborales tanto a nivel agregado como desagregado, para el análisis de la volatilidad y la naturaleza de los shocks que generan las fluctuaciones del mercado laboral, la coexistencia de desempleo y vacantes y como una aproximación al proceso de matching y eficiencia del mercado laboral^[Por si sola la CB solo puede ser una aproximación a la eficiencia del mercado laboral puesto que es necesario ampliar el análisis y tomar en cuenta los flujos de trabajadores, tanto la creación como la destrucción de puestos laborales]. -->


<!-- El matching se fundamenta en el marco DMP -->
<!-- El proceso de matching se relaciona con los diferentes componentes del desempleo, estructural y friccional\footnote{El desempleo cíclico o keyneasiano, se asocia al desempleo generado por el ciclo económico. En nuestro caso, no es necesario agregar esta categoría puesto que lo analizamos de la misma forma que el desempleo estructural, como movimientos sobre la CB}, los cuales puede ser analizados mediante la CB a través del marco DMP. -->

<!-- Análisis de los distintos tipos de desempleo, relacionar a las reformas uruguayas -->
<!-- El desempleo friccional refiere a personas que buscan trabajo o un cambio laboral\footnote{Esta clase de desempleo se dice que es intrínsecamente voluntario. Sin embargo, el motivo por el cual el sujeto busca o cambia de trabajo se asocia a situaciones involuntarias.}. Se ve afectado por modificaciones en la función de matching o aumentos en la tasa de destrucción de puestos laborales. Esto puede ser interpretado como alteraciones en la eficiencia laboral generando traslados paralelos de la CB, un corrimiento hacia el origen implicaría una mejora del match (un traslado hacia afuera un empeoramiento). Causas de cambios en la función de matching pueden ser los costos de contratación y despido, modificaciones sobre el salario mínimo, la existencia de derecho a huelga y ocupación, la sindicalización, la facilidad de la mano de obra para moverse geográficamente (cambios en la PEA), modificaciones en las habilidades de los trabajadores y creación de portales laborales en Internet que disminuyan el tiempo de búsqueda. -->

<!-- El desempleo estructural es la discordancia entre habilidades ofrecidas por trabajadores y demandadas por firmas. Se asocia a cambios tecnológicos (shocks de productividad) los cuales requieren menor nivel de empleo y una demanda laboral por habilidades que el trabajador no puede ofrecer generando un exceso de oferta laboral. Esto implica mayor tasa de desempleo y menor cantidad de vacantes laborales o sea movimientos sobre la CB. El lugar donde nos encontramos sobre la curva puede estar indicando en que parte del ciclo económico se sitúa la economía. Si la posición es un punto con altas vacantes y bajo desempleo sería una etapa expansiva, en caso contrario una fase recesiva\footnote{Lo cual explicaría el desempleo de cíclico}. -->

<!-- Por ejemplo, en la década de los noventa Uruguay transitó una apertura de su cuenta corriente y de capitales lo cual genero un efecto relevante en el mercado laboral, ya que, las empresas locales no fueron capaces de competir con los productos importados, siendo un periodo de crecimiento económico y alto desempleo [@Antia2001]. El gobierno dejó de participar de los consejos de salarios a partir de 1992 dando libertad de acción a la negociación entre empresas y trabajadores [@Antia2001]. Fue una clara promoción a la negociación por empresa en contraposición a la negociación por rama de actividad, mientras la primera aumento de forma considerable la segunda cayó abruptamente [@Filgueira2003].  -->

<!-- Construida la serie de vacantes, se sistematizan los datos de desempleo y se busca responder la pregunta y testear las hipótesis utilizando dos estrategias empíricas. Los test de quiebres estructurales [@Andrews1991;@Andrews1994;@BaiPerron1998;@BaiPerron2003;@Zeileis2010] con los cuales se pone a prueba la hipótesis nula de no existencia de un cambio estructural en la relación de vacantes y desempleo, estimando las CB para los periodos obtenidos. Por último, utilizando vectores autorregresivos con parámetros variables y volatilidad estocástica, TVP-VAR o TVP-VAR-SV [@Nakajima2011;@Benati2013;@Primiceri2005;@Lubik2016b], identificado bajo un modelo básico de búsqueda y emparejamiento, con restricciones de identificación de Cholesky y estimado de forma bayesiana mediante el muestreo de Gibbs. -->

La organización del documento es la siguiente:

* **[Capítulo 2](#cap:Fundamentos):** revisa la literatura de la curva de Beveridge en Uruguay, Estados Unidos y Europa. Expone la teoría de Búsqueda y Emparejamiento.

* **[Capítulo 3](#cap:Datos):** define conceptos y fuentes de datos.

* **[Capítulo 4](#cap:Metodología):** revisa la metodología de quiebres estructurales y TVP-VAR.

* **[Capítulo 5](#cap:Resultados):** presenta los resultados, creación del índice de vacantes, estimación de la CB, test de quiebres estructurales y la estimación de un TVP-VAR

* **[Capítulo 6](#cap:Discusion):** discute mejoras y posibles comentarios del indicador de vacantes y los resultados obtenidos de la estimación de la CB.

* **[Capítulo 7](#cap:Conclusiones):** exhibe las conclusiones de la investigación y posibles trabajos futuros producto de la tesis, en especial posibles lineas de investigación futuras.
