# Curva de Beveridge {#cap:Fundamentos}

## Revisión de literatura

<!-- Revisión Literatura -->
<!-- @Elsby2015 muestran que la CB se utiliza a nivel macroeconómico como un marco de análisis para el entendimiento de los mercados laborales tanto a nivel agregado como desagregado, para el análisis de la volatilidad y la naturaleza de los shocks que generan las fluctuaciones del mercado laboral, la coexistencia de desempleo y vacantes y como una aproximación al proceso de matching y eficiencia del mercado laboral^[Por si sola la CB solo puede ser una aproximación a la eficiencia del mercado laboral puesto que es necesario ampliar el análisis y tomar en cuenta los flujos de trabajadores, tanto la creación como la destrucción de puestos laborales]. -->
<!-- La CB ha sido utilizada para descomponer el desempleo en diferentes tipos, clarificar el debate respecto al pleno empleo y como un punto de discordancia respecto al vaciamiento de los mercados competitivos.  -->
<!-- Mientras en los años sesenta y setenta fue ampliamente empleada en la década de los ochenta su uso cayó notablemente al punto de ser casi abandonada, entre otras causas, por su falta de microfundamentos [@Rodenburg2007]. Resurge en los noventa gracias al trabajo de @Blanchard1989 quienes remarcan el error que la CB haya ocupado un lugar secundario en la macroeconomía dado que contiene información esencial sobre el funcionamiento del mercado de trabajo y shocks que afecten al mismo. -->
<!-- Actualmente ha logrado volverse el marco de análisis central en la macroeconomía laboral [@Elsby2015] gracias a los trabajos de @Pissarides1985, @Mortensen1994 y @Diamond1982 quienes dieron microfundamentos a la relación entre vacantes y desempleo permitiendo derivar una forma analítica que surge de las decisiones de optimizaciones de los agentes del modelo. Hecho relevante al permitir que la CB sea utilizada para el análisis de la política económica al estar exenta de la crítica de Lucas^[La crítica de Lucas fue un claro ataque a los modelos de ecuaciones simultáneas y por sobre todo a la no inclusión de microfundamentos en el análisis macroeconómico lo cual invalidaba cualquier calculo sobre el efecto de una política económica, falla típica de los modelos keynesianos [@Lucas1976]. Una respuesta posterior surgió por parte de la econometría bajo el trabajo de @exogeneity1983 según el cual pese a que un modelo no tenga microfundamentos si cumple la superexogeneidad el mismo puede ser utilizado para simular política económicas.]. Permitiendo estudiar las reacciones de vacantes y desempleo ante shocks de productividad [@Benati2013], la estabilidad paramétrica en la relación [@Lubik2016] y las causas que generan traslados o movimientos sobre la CB desde una perspectiva dinámica. -->
<!-- Análisis de la OECD: Inglaterra y que otro? -->
@Beveridge es pionero en identificar las vacantes laborales como un determinante de la tasa de desempleo y, encontrar una relación negativa entre ambas variables. @Dicks-Mireaux1958 plantean por primera vez la CB gráficamente al examinar la confiabilidad del uso de vacantes y desempleo para ilustrar tendencias en la demanda de trabajo. Entienden y utilizan la CB para medir el exceso de demanda en el mercado de trabajo como un indicador del exceso de demanda en el mercado de bienes. 

A nivel europeo en los años sesenta y setenta se genera una gran cantidad de trabajos, principalmente en Inglaterra, los cuales buscaban explicar los traslados de la CB [@Rodenburg2007].^[Según @Rodenburg2007 en los años 1980 la CB tuvo un periodo de baja utilización debido en parte a la falta de microfundamentos de la CB, lo cual genera que cualquier análisis de política económica fuese plausible de la crítica de @Lucas1976. Con el establecimiento del marco DMP dicha crítica desaparece.] Por ejemplo, @Gujarati1972 considera que el traslado de la CB (1958-1972) en Inglaterra se debió a factores institucionales debido al Redundancy Payment Act. @Bewley1979 halla resultados similares y agrega que el movimiento de la CB se asoció a factores demográficos que disminuyeron la eficiencia de la búsqueda laboral en conjunto a variaciones en los flujos de destrucción de puestos laborales (renuncias y despidos). @Evans1977 lo asocia a la diferencia entre desempleo total y desempleo registrado, mostrando que las proporciones de personas registradas como desempleadas varían considerablemente entre regiones y en el tiempo.
<!-- ^[El estudio fue novedoso en la medida que utilizó la discriminación por sexo en las vacantes laborales. Lo cual fue prohibido a partir de 1976 en Inglaterra. @Chew1986 realizan un estudio similar entre 1965-1980 para Singapur]. -->

@Nickell2002 estudian los mercados laborales de países de la OCDE entre 1960 y 1990 hallando traslados de la CB para todos los países a excepción de Noruega y Suecia. El motivo principal son las modificaciones en las instituciones del mercado laboral, como la unión sindical y las protecciones en el empleo. @Bouvet2012 detecta resultados similares en Alemania, Bélgica, Holanda, España y Reino Unido entre 1975 y 2004 donde los traslados en la curva se deben a rigideces del mercado laboral, como aumentos de salarios mínimos y elevados seguros de desempleo, sumado al desempleo de largo plazo generando _histeresis_. @Hobijn2013 <!-- analizan países europeos --> <!-- y EEUU --> encuentra desplazamientos de la fuerza laboral en las recesiones que generan un cambio en la composición de vacantes disminuyendo la eficiencia del matching, lo cual se ve compensado por la disminución en la tasa de abandono (separaciones, sin incluir los despidos).  <!-- Para EEUU encuentran que la Gran Recesión generó traslados de la CB por un tiempo superior al que podría esperarse según @Mortensen1994.  -->  <!-- @Elsby2015 señala que entre 1970 y 1980 la CB de países europeos ha tenido traslados debido a cambios en la eficiencia de los procesos de contratación.  --> <!-- Dicho resultado se repite para EEUU a partir de la Gran Recesión. -->

<!-- EEUU -->
En los EEUU @Abraham1987 genera un índice ajustado del proxy de vacantes basado en el help-wanted-index que asocia los movimientos en la CB a cambios en la composición del empleo, en la dispersión de la demanda laboral entre sectores de actividad y alteraciones en los comportamientos de búsqueda. @Blanchard1989 utilizan datos de vacantes, desempleo y fuerza laboral para identificar variaciones en el desempleo y tasa de vacantes debido a shocks cíclicos (demanda agregada), sectoriales (realocación) y shocks de oferta. Determinan que en el largo plazo son los shocks sectoriales y una tendencia determinista los que generan los traslados de la CB, mientras en el corto plazo los shocks de oferta agregada generan un movimiento sobre la curva.<!-- como insumo desarrollan una función de matching Cobb-Douglas con retornos constantes para EEUU estimada mediante MCO. --> <!-- @Barnichon2010 construye un índice de vacantes compuesto por el Help-Wanted Index (HWI) en papel, que recolecta las búsquedas laborales en los 51 mayores periódicos y, el HWI en linea del Conference Board que recolecta los avisos publicados en portales laborales web desde 2005^[trabajos previos pueden encontrarse en @Barnichon2009.]. --> @Hobijn2013 consideran que la Gran Recesión generó traslados de la CB por un tiempo superior al que podría esperar según @Mortensen1994, además de dezplazamientos de la fuerza laboral que genero un cambio en la composión de vacantes disminuyendo la eficiencia del matching. 
<!-- @Elsby2015 encuentra que los traslados de la CB posterior a la gran recesión se deben a cambios en la eficiencia de los procesos de contratación. -->
@Benati2013 usando los datos generados por @Barnichon2010 y la metodología de @Stock1996 y @Stock1998 ponen a prueba la variabilidad paramétrica entre vacantes y desempleo con lo cual estiman un TVP-VAR donde la evolución de los traslados de la CB es similar a observada para el periodo recesivo de la era Volcker, identificando cambios similares desde 1960. @Lubik2013 siguiendo la misma metodología TVP-VAR afirma que el traslado de la CB luego de la Gran Recesión puede ser explicado por la interacción de una caída cíclica de la productividad y una disminución en la eficiencia del matching. @Lubik2016 plantean un modelo de Búsqueda y Emparejamiento con el cual encuentran un cambio estructural en la CB, sin embargo al plantear un TVP-VAR no observan transformaciones en los parámetros de las variables endógenas pero si modificaciones en la matriz de varianzas y covarianzas (VCV). Concluyendo que un TVP-VAR puede asociar cambios estructurales a variaciones temporales en la matriz de VCV de los shocks.

@Hobijn2013 encuentra tanto para EEUU como países europeos cambios en la composición de vacantes. @Elsby2015 resumen hallazos previos para Europa y EEUU, mencionando movimientos y traslados de la CB similares entre algunos países europeos como Holanda y los EEUU. Efecto guiado por los cambios en los procesos de contratación lo cual es un resultado interesante en la medida que las instituciones del mercado laboral difieren fuertemente al ser Europa un mercado laboral más regulado.
<!-- @Elsby2015 -->

 <!-- @Diamond2015,  -->
<!-- Resto del mundo -->

<!-- Análisis AL -->
A nivel sudamericano la cantidad de trabajos es escasa comparativamente debido a la ausencia de series de vacantes laborales, por eso, suelen compartir la necesidad de construir un indicador de vacantes. En Chile @BankChile2002 crean un índice de vacantes utilizando los puestos laborales solicitados en los avisos laborales de periódicos para las cinco mayores áreas urbanas desde 1986 hasta 2002.
En Argentina @ArgentinaBC2019 utilizan encuestas sobre posiciones abiertas recolectadas por el Ministerio de Trabajo y construyen un índice de vacantes siguiendo la metodología expuesta por @Barnichon2010.

<!-- Análisis de Uruguay -->
Los trabajos en Uruguay comienzan con @Rama1988 quien utiliza la CB con fines descriptivos para aproximarse a la descomposición de la desocupación en desempleo voluntario, de segmentación y desequilibrio. Es el primer trabajo en Uruguay en plantear gráficamente la CB (1978-1988) y construir un índice de vacantes. Su objetivo es cuantificar los componentes de la desocupación analizando la agregación de micro mercados de trabajo mediante un modelo de desequilibrio. Plantea que la CB puede utilizarse para cuantificar los componentes de segmentación y desequilibrio, no así el componente voluntario debido a las variaciones de la PEA en la década de 1980. <!-- Pero al dividirlo por la pea, eso no esta tomado en cuenta??? --> @DECON1993 estiman mediante una regresión lineal la CB entre 1980 y 1990 en la cual encuentran evidencia de una tendencia de la curva a desplazarse hacia afuera, indicando un mercado de trabajo con mayor rigidez, aunque se demarcan que la razón fundamental de ello sean salarios relativos inadecuados. @Urrestarazu1997 construye en base al trabajo y serie de @Rama1988 y extiende el periodo de análisis hasta el año 1995. Si bien su foco al igual que Rama es el estudio del desempleo de segmentación y los micro mercados mediante modelos de desequilibrio, estima por mínimos cuadrados ordinarios (MCO) una CB. Siguiendo a @Chow1960 mediante una estimación restringida y otra no restringida pone a prueba la hipótesis de que exista un cambio estructural en 1990. Sus resultados concluyen que se rechaza la hipótesis nula de no existencia de un cambio estructural entre 1980 y 1995. <!-- Sin embargo, advierte siguiendo a Rama que las conclusiones obtenidas solo son válidas en la medida que la evolución del desempleo voluntario sea estable. --> <!-- , característica común en países desarrollados, pero no así en Uruguay.  --> Finalmente, @Alma2011 obtienen datos de puestos laborales a partir de las publicaciones de prensa en las primeras dos semanas de los meses de marzo, mayo o junio y septiembre entre 2000 y 2009, con lo cual construyen una CB anual utilizada con fines ilustrativos para mostrar una relación inversa y negativa para el periodo 2000-2009. Los autores hacen referencia a un posible cambio de pendiente en la curva, sin embargo, dada la escasez de datos afirman que no es posible identificar alteraciones relevantes.

Este trabajo se siguen los últimos trabajos de @Benati2013, @Lubik2013 y @Lubik2016 al estimar un TVP-VAR para analizar la existencia de cambios en la CB que puedan estar asociados a modificaciones en la media o shocks idiosincraticos que alteren la volatilidad de la relación entre vacantes y desempleo. Adicionalmente, se utilizan test de quiebres estructurales como en @Urrestarazu1997, aunque los mismos son generalizados y no requieren especificar el punto de quiebre. Finalmente, se da un paso más al utilizar un test que permiten encontrar múltiples quiebres estructurales en la CB, tanto en media como en varianza.
<!-- Agregar trabajo del BID sobre vacantes -->
<!-- Agregar trabajos de Chile sobre vacantes, ver los citados en Alma Espino del iecon -->

## Teoría de Búsqueda y Emparejamiento

Es posible enmarcar la CB bajo la teoría de búsqueda y emparejamiento utilizando el modelo básico de @Pissarides2000 con el cual derivar una forma analítica de la curva suponiendo la existencia de una función de matching, un proceso estocástico de Poisson mediante el cual se llenan las vacantes y que en estado estacionario la tasa de variación de la tasa de desempleo debe ser nula. Conceptualmente modificaciones en la función de matching generan traslados de la CB. Así como alteraciones en la función de producción generan una economía con mayor o menor capacidad de producción, la función de matching refleja una economía donde el match entre trabajador y firma puede ser más rápido o lento, por lo tanto, el mercado laboral puede ser más o menos eficiente (deben considerarse los flujos). 

El _matching_ es un proceso estocástico sujeto a una tecnología o función de producción (denominada función de _matching_) donde interactúan firmas (demanda) y trabajadores (oferta) quienes guían sus decisiones optimizando sus funciones objetivos dada su información disponible (imperfecta) y restricciones. La contratación del trabajador (el match) resulta de una búsqueda aleatoria y negociación (a la nash y en general asimétrica) que satisface ciertas condiciones salariales negociadas por ambas partes.
En este proceso el trabajador incurre en costos de búsqueda y pierde beneficios potenciales en otras actividades, valora el ingreso salarial y condiciones laborales presentes (decisión estática) y el flujo de ingresos futuros y condiciones laborales futuras (factores monetarios y no monetarios que implican una decisión dinámica). La firma tiene costos de búsqueda los cuales internaliza en conjunto a los potenciales costos de capacitación y posible fin de la relación laboral futura, por lo cual calcula el valor presente del costo de la vacante y sus beneficios potenciales. Este proceso de decisión es inherentemente dinámico, descoordinado, con fricciones, riesgos y asimetrías de información que generan una diferencia sistemática entre demanda y oferta laboral.^[Estudios sobre el proceso de _matching_ puede verse en @Pissarides2000 y @Elsby2015 mientras inspecciones sobre la función de _matching_ en @Petrongolo2001.]

En la ecuación \eqref{eq7} ($u = \frac{\lambda}{\lambda+\theta q(\theta)}$) puede observarse como transformaciones de $\theta$, cociente entre vacantes y tasa de desempleo, genera movimientos sobre la curva asociados al ciclo económico. Modificaciones de q($\theta$), que reflejen cambios en la función de matching $m$ o alteraciones en $\lambda$, incertidumbre que sufre el trabajador de perder los beneficios de un puesto ocupado, van a generar corrimientos de la curva.

Cambios en la función de matching pueden asociarse a una diferencia entre las habilidades requeridas por las firmas y las ofrecidas por los trabajadores. Por ejemplo, si los cambios tecnológicos son sesgados hacia la utilización del capital, nuevas tecnologías y personas con alta capacitación. Si este fuese el caso, tanto las vacantes laborales como la tasa de desempleo pueden aumentar, o crecer solamente el desempleo para una misma tasa de vacantes. Los shocks sobre la función de matching pueden tener un carácter permanente o transitorio, por ejemplo, una reforma estructural, como las políticas sociales, en especial las nuevas relaciones laborales mencionadas en @Bergara2017 deberían tener un efecto permanente.

El modelo básico también permite ver como una economía en la cual los trabajadores enfrenten un riesgo mayor de perder los beneficios de un puesto ocupado, mayor $\lambda$, genera un mercado laboral menos eficiente. El caso extremo de $\lambda=0$, nos lleva a un punto de la curva que se situaría sobre el origen, un mercado sin desempleo ni vacantes. Si bien dicho caso es irrelevante en términos prácticos, muestra que sin la existencia del riesgo de perdida laboral y sin trabajadores que transiten del empleo al desempleo (ecuación \eqref{eq4} sería cero), estaríamos en una economía completamente eficiente. Es decir, el riesgo y los flujos laborales son relevantes para cuantificar la eficiencia de un mercado laboral.

<!-- Este párrafo me parece que esta mal, revisarlo y si no logro arreglarlo lo borro -->
Modificaciones en el riesgo pueden deberse a reformas que hayan cambiado las reglas en el ámbito laboral aumentando la protección de los trabajadores. Los flujos podrían verse alterados por innovaciones tecnológicas como portales laborales que faciliten el match entre trabajador y empresa. Si bien $\lambda$ es una variable exógena en el modelo, podemos pensar dichos cambios como variaciones en ella, siendo los mismos shocks transitorios o estructurales.

<!-- El _matching_ es un proceso estocástico sujeto a una tecnología o función de producción (denominada función de _matching_) donde interactúan firmas (demanda) y trabajadores (oferta) quienes guían sus decisiones optimizando sus funciones objetivos dada su información disponible (imperfecta) y restricciones. La contratación del trabajador (el match) resulta de una búsqueda aleatoria y negociación (a la nash y en general asimétrica) que satisface ciertas condiciones salariales negociadas por ambas partes. -->
<!-- En este proceso el trabajador incurre en costos de búsqueda y pierde beneficios potenciales en otras actividades, valora el ingreso salarial y condiciones laborales presentes (decisión estática) y el flujo de ingresos futuros y condiciones laborales futuras (factores monetarios y no monetarios que implican una decisión dinámica). La firma tiene costos de búsqueda los cuales internaliza en conjunto a los potenciales costos de capacitación y posible fin de la relación laboral futura, por lo cual calcula el valor presente del costo de la vacante y sus beneficios potenciales. Este proceso de decisión es inherentemente dinámico, descoordinado, con fricciones, riesgos y asimetrías de información que generan una diferencia sistemática entre demanda y oferta laboral <!-- más allá del desempleo voluntario. -->
<!-- Estudios sobre el proceso de _matching_ puede verse en @Pissarides2000 y @Elsby2015 mientras inspecciones sobre la función de _matching_ en @Petrongolo2001. -->

