# Conclusión {#cap:Conclusiones}

Este trabajo ha creado una base de datos de cantidad de avisos laborales, con la cual se calcula un índice de vacantes laborales que busca reflejar la demanda laboral por parte de las empresas en Montevideo, en la medida que la capital concentra cerca del 50% de la población y una parte importante de la producción la misma debería ser representativa de los movimientos de vacantes a nivel Nacional. Se ha logrado generar una serie desde 1980-I hasta 2019-IV siendo la única serie de vacantes laborales actualizada en Uruguay. Se ha escrito el código en lenguaje _R_, código público y reproducible, para poder obtener la información de avisos laborales futuros, lo cual da pie a que el periodo de análisis se pueda seguir extendiendo de forma ininterrumpida, aumentado las fuentes de datos y dotando de una herramienta clave como la Curva de Beveridge a la política económica.

Es de interés que el índice de vacantes construido sea perfeccionado en trabajos futuros o se intente aplicar otras metodologías (por ejemplo @Barnichon2010), se agreguen nuevas fuentes de información (como Linkedin) y se mejoren datos previos. En especial durante el periodo de 2000 a 2012 en el cual se utiliza una serie filtrada sin conocimiento detallado de la transformación aplicada. Adicionalmente, es posible reducir la frecuencia de las series de trimestral a mensual. O yendo aún más lejos, la serie de vacantes podría llegar a ser semanal y que se pruebe su utilidad como un indicador adelantado de la actividad.

Una vez perfeccionado el indicador, se podría calcular tanto la tendencia como el ciclo de la serie de vacantes mediante la aplicación del filtro de Hamilton y hacer un análisis conjunto con PIB y desempleo en el dominio de frecuencias, para poder analizar en que etapa del ciclo se encuentra el proxy de la demanda laboral.

<!-- Se han buscado cambios estructurales en el mercado laboral mediante diferentes metodologías de quiebres estructurales. En todos los casos se ha llegado a la conclusión de rechazar la hipótesis de no existencia de quiebre en el proceso generador de datos. Se analiza en que momento la economía ha transitado esos cambios, encontrando tres o cuatro puntos de quiebre, lo que indica cuatro o cinco periodos de tiempo. Siendo reservados en cuanto a los quiebres podemos mantener que el mercado laboral ha transitado por cuatro periodos. Desde 1980 hasta 1990, siendo este un periodo de mayor eficiencia laboral (entendiendo a la misma como una CB más cercana al origen), de 1990 hasta 1996, lo que puede verse como un deterioro del mercado laboral con menos vacantes y mayor desempleo. Son años de transición, que se enmarcan dentro de los cambios que tuvo la economía uruguaya a principio de 1990, modificaciones importantes que abrieron fuertemente la economía siendo un periodo de crecimiento moderado y alto desempleo.  -->

<!-- Desde 1996 hasta 2013, donde tenemos la recesión que comienza la economía uruguaya a partir de 1998, con la posterior crisis económica y social de 2001-2002. Esto genera caídas abruptas en las vacantes y un aumento explosivo de la tasa de desempleo, a partir del tercer trimestre de 2003 la economía comienza un período de crecimiento ininterrumpido hasta el día de hoy. Entre 2005 y 2010 se procesan fuertes reformas económicas y sociales, que pueden haber afectado al mercado laboral. Penetra la tecnología en los procesos de contratación, pasando de búsquedas por periódicos a portales web de búsqueda laboral, el mercado laboral tiene una transición paralela en la CB hacia el origen, notando la menor tasa de desempleo para igual cantidad de búsquedas. El hecho que se observe una caída importante en las vacantes laborales y que la tasa de desempleo se haya mantenido relativamente estable en torno a 7-9\%, podría estar indicando que las reformas de la economía uruguaya han generado un mercado laboral más eficiente que logra soportar una menor demanda laboral de las empresas sin aumentar dramáticamente la tasa de desempleo.  -->

Es de hacer notar que las caídas observadas en las vacantes laborales son de orden similar a las observadas en 1982 y 2002, sin embargo la tasa de desempleo en ningún momento ha llegado a niveles similares. La única forma en que la economía soporte tal nivel de caída en la demanda laboral, es que el matching en el mercado laboral haya aumentado de forma considerable. El factor institucional es imposible no este presente dada la cantidad de reformas de caracter estructural y modificaciones en las instituciones del mercado laboral. Pero no es el único, ademas de los factores cíclicos, un factor posiblemente relevante, son los portales laborales de Internet y el avance tecnológico que permiten una búsqueda y proceso de contratación a una velocidad comparativamente mayor que los procesos iniciados mediante la prensa en papel. Las agencias de contratación (y los mismos portales) pueden manejar enormes volúmenes de información sobre posibles candidatos que permiten una búsqueda sobre un universo mayor e incluso de forma selecta. Sería interesante, agregar al trabajo un análisis sobre los flujos laborales para poder corroborar la mejora en el proceso de matching.

Por último, utilizando la metodología TVP-VAR no observamos modificación en los parámetros asociados a la media condicional y las modificaciones en las matrices de varianzas y covarianzas son leves o nulas. Sin embargo, las FIR por un shock del producto a vacantes y desempleo tiene efectos significativos. La lectura sería que los traslados paralelos observados de la CB se deben a shocks con efectos significativos de signo opuesto. Si bien la economía ha tenido fuertes shocks externos, dada la cantidad de reformas que pueden catalogarse de estructurales, sería llamativo que la variabilidad en vacantes y desempleo pueda deberse solamente a innovaciones.

Es posible profundizar sobre los modelos TVP-VAR, haciendo un análisis de priors y sus efectos, a la vez que probar y/o combinar diferentes restricciones de identificación y realizar el análisis con las series mensuales.

Finalmente es de interés para la política económica identificar cuales son las causas que están detrás de los traslados de la CB en la medida que se puedan tomar acciones para mejorar la eficiencia del mercado laboral. Por lo que es necesario que trabajos futuros investiguen al respecto.

<!-- Finalmente, es llamativo que periodos con políticas laborales tan diferentes como los 90 y 2010 tengan un comportamiento similar en cuanto al crecimiento de la actividad y aumento del desempleo. -->

